// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// UserProfile contains the user personal information
type UserProfile struct {
	// Id is the user id which uniquely identify a user
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Email is the unique email of the user
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// FirstName is the user first name,it does not have any min length as it can
	// be empty too.
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// LastName is the user last Name , it does not have any min length as it can
	// be empty too.
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}
func (*UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *UserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfile.Unmarshal(m, b)
}
func (m *UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfile.Marshal(b, m, deterministic)
}
func (m *UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfile.Merge(m, src)
}
func (m *UserProfile) XXX_Size() int {
	return xxx_messageInfo_UserProfile.Size(m)
}
func (m *UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfile proto.InternalMessageInfo

func (m *UserProfile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserProfile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserProfile) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserProfile) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type CreateUserProfileRequest struct {
	UserProfile          *UserProfile `protobuf:"bytes,1,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateUserProfileRequest) Reset()         { *m = CreateUserProfileRequest{} }
func (m *CreateUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserProfileRequest) ProtoMessage()    {}
func (*CreateUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *CreateUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserProfileRequest.Unmarshal(m, b)
}
func (m *CreateUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserProfileRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserProfileRequest.Merge(m, src)
}
func (m *CreateUserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserProfileRequest.Size(m)
}
func (m *CreateUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserProfileRequest proto.InternalMessageInfo

func (m *CreateUserProfileRequest) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type GetUserProfileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserProfileRequest) Reset()         { *m = GetUserProfileRequest{} }
func (m *GetUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserProfileRequest) ProtoMessage()    {}
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}

func (m *GetUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserProfileRequest.Unmarshal(m, b)
}
func (m *GetUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserProfileRequest.Merge(m, src)
}
func (m *GetUserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserProfileRequest.Size(m)
}
func (m *GetUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserProfileRequest proto.InternalMessageInfo

func (m *GetUserProfileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteUserProfileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserProfileRequest) Reset()         { *m = DeleteUserProfileRequest{} }
func (m *DeleteUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserProfileRequest) ProtoMessage()    {}
func (*DeleteUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{3}
}

func (m *DeleteUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserProfileRequest.Unmarshal(m, b)
}
func (m *DeleteUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserProfileRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserProfileRequest.Merge(m, src)
}
func (m *DeleteUserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserProfileRequest.Size(m)
}
func (m *DeleteUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserProfileRequest proto.InternalMessageInfo

func (m *DeleteUserProfileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateUserProfileRequest struct {
	UserProfile          *UserProfile `protobuf:"bytes,1,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateUserProfileRequest) Reset()         { *m = UpdateUserProfileRequest{} }
func (m *UpdateUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserProfileRequest) ProtoMessage()    {}
func (*UpdateUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{4}
}

func (m *UpdateUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserProfileRequest.Unmarshal(m, b)
}
func (m *UpdateUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserProfileRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserProfileRequest.Merge(m, src)
}
func (m *UpdateUserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserProfileRequest.Size(m)
}
func (m *UpdateUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserProfileRequest proto.InternalMessageInfo

func (m *UpdateUserProfileRequest) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type ListUsersProfilesRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersProfilesRequest) Reset()         { *m = ListUsersProfilesRequest{} }
func (m *ListUsersProfilesRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersProfilesRequest) ProtoMessage()    {}
func (*ListUsersProfilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{5}
}

func (m *ListUsersProfilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersProfilesRequest.Unmarshal(m, b)
}
func (m *ListUsersProfilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersProfilesRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersProfilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersProfilesRequest.Merge(m, src)
}
func (m *ListUsersProfilesRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersProfilesRequest.Size(m)
}
func (m *ListUsersProfilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersProfilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersProfilesRequest proto.InternalMessageInfo

func (m *ListUsersProfilesRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type ListUsersProfilesResponse struct {
	Profiles             []*UserProfile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListUsersProfilesResponse) Reset()         { *m = ListUsersProfilesResponse{} }
func (m *ListUsersProfilesResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersProfilesResponse) ProtoMessage()    {}
func (*ListUsersProfilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{6}
}

func (m *ListUsersProfilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersProfilesResponse.Unmarshal(m, b)
}
func (m *ListUsersProfilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersProfilesResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersProfilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersProfilesResponse.Merge(m, src)
}
func (m *ListUsersProfilesResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersProfilesResponse.Size(m)
}
func (m *ListUsersProfilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersProfilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersProfilesResponse proto.InternalMessageInfo

func (m *ListUsersProfilesResponse) GetProfiles() []*UserProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func init() {
	proto.RegisterType((*UserProfile)(nil), "proto.UserProfile")
	proto.RegisterType((*CreateUserProfileRequest)(nil), "proto.CreateUserProfileRequest")
	proto.RegisterType((*GetUserProfileRequest)(nil), "proto.GetUserProfileRequest")
	proto.RegisterType((*DeleteUserProfileRequest)(nil), "proto.DeleteUserProfileRequest")
	proto.RegisterType((*UpdateUserProfileRequest)(nil), "proto.UpdateUserProfileRequest")
	proto.RegisterType((*ListUsersProfilesRequest)(nil), "proto.ListUsersProfilesRequest")
	proto.RegisterType((*ListUsersProfilesResponse)(nil), "proto.ListUsersProfilesResponse")
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8) }

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xdd, 0x4a, 0xc3, 0x30,
	0x14, 0xc7, 0xf7, 0xe1, 0x64, 0x3d, 0x1d, 0x83, 0x85, 0x29, 0xb1, 0x53, 0x1c, 0xb9, 0x51, 0xbc,
	0xe8, 0x64, 0xe2, 0x0b, 0xe8, 0x44, 0x50, 0x19, 0x6e, 0x30, 0x10, 0x6f, 0x46, 0x65, 0x67, 0xa3,
	0xd0, 0xae, 0x59, 0xd2, 0x5e, 0xec, 0x45, 0x7c, 0x5e, 0x69, 0xd2, 0xd5, 0xb9, 0x36, 0x77, 0xde,
	0x34, 0x9c, 0x8f, 0xfc, 0xcf, 0x3f, 0xfc, 0x4e, 0xc1, 0xe6, 0x22, 0x8a, 0x23, 0x57, 0x7d, 0x49,
	0x43, 0x1d, 0x4e, 0x6f, 0x15, 0x45, 0xab, 0x00, 0x07, 0x2a, 0xfa, 0x4a, 0x96, 0x03, 0x0c, 0x79,
	0xbc, 0xd5, 0x3d, 0x2c, 0x02, 0x7b, 0x26, 0x51, 0xbc, 0x8b, 0x68, 0xe9, 0x07, 0x48, 0xda, 0x50,
	0xf3, 0x17, 0xb4, 0xda, 0xaf, 0x5e, 0x5b, 0xd3, 0x9a, 0xbf, 0x20, 0x5d, 0x68, 0x60, 0xe8, 0xf9,
	0x01, 0xad, 0xa9, 0x94, 0x0e, 0xc8, 0x05, 0xc0, 0xd2, 0x17, 0x32, 0x9e, 0xaf, 0xbd, 0x10, 0x69,
	0x5d, 0x95, 0x2c, 0x95, 0x19, 0x7b, 0x21, 0x92, 0x1e, 0x58, 0x81, 0xb7, 0xab, 0x1e, 0xa9, 0x6a,
	0x33, 0x4d, 0xa4, 0x45, 0x36, 0x01, 0xfa, 0x28, 0xd0, 0x8b, 0x71, 0x6f, 0xec, 0x14, 0x37, 0x09,
	0xca, 0x98, 0xdc, 0x43, 0x2b, 0x91, 0x28, 0xe6, 0x5c, 0xa7, 0x95, 0x0f, 0x7b, 0x48, 0xb4, 0x55,
	0x77, 0xff, 0x82, 0x9d, 0xfc, 0x06, 0xec, 0x0a, 0x4e, 0x9e, 0x31, 0x2e, 0xd1, 0x3b, 0x78, 0x0d,
	0xbb, 0x01, 0x3a, 0xc2, 0x00, 0x4b, 0x67, 0x1f, 0xf6, 0x4e, 0x80, 0xce, 0xf8, 0xe2, 0x5f, 0x7d,
	0xde, 0x02, 0x7d, 0xf3, 0xa5, 0x32, 0x2a, 0xb3, 0x9c, 0xdc, 0x49, 0x76, 0xa1, 0xb1, 0x49, 0x50,
	0x6c, 0x33, 0x07, 0x3a, 0x60, 0xaf, 0x70, 0x56, 0x72, 0x43, 0xf2, 0x68, 0x2d, 0x91, 0xb8, 0xd0,
	0xcc, 0x0c, 0x48, 0x5a, 0xed, 0xd7, 0x0d, 0x0e, 0xf2, 0x9e, 0xe1, 0x77, 0x1d, 0x5a, 0x7b, 0x15,
	0x49, 0x5e, 0xa0, 0x53, 0x40, 0x41, 0x2e, 0x33, 0x0d, 0x13, 0x24, 0xa7, 0x64, 0x08, 0xab, 0x90,
	0x11, 0xb4, 0xff, 0x32, 0x20, 0xe7, 0x59, 0x5f, 0x29, 0x1a, 0x83, 0xca, 0x18, 0x3a, 0x05, 0x40,
	0xb9, 0x23, 0x13, 0x3a, 0xe7, 0xd4, 0xd5, 0x1b, 0xee, 0xee, 0x36, 0xdc, 0x7d, 0x4a, 0x37, 0x9c,
	0x55, 0xd2, 0x17, 0x16, 0x20, 0xe6, 0x7a, 0x26, 0xbc, 0x06, 0x6f, 0x1f, 0xd0, 0x29, 0xb0, 0xc8,
	0xb5, 0x4c, 0x5c, 0x9d, 0xbe, 0xb9, 0x41, 0x63, 0x64, 0x95, 0x07, 0xfb, 0xd3, 0xf2, 0x38, 0xcf,
	0xfe, 0xcf, 0x63, 0x75, 0xdc, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x53, 0x53, 0x1b, 0xca,
	0x03, 0x00, 0x00,
}
